pub(crate) mod agent_adapter;
pub(crate) mod agent_bridge;
#[cfg(test)]
mod agent_conformance;
pub(crate) mod agent_integration;
pub mod agent_protocol;
pub(crate) mod agent_route;
pub(crate) mod agent_session;
pub(crate) mod claude_adapter;
pub(crate) mod claude_hook;
pub(crate) mod claude_integration;
pub(crate) mod claude_managed_adapter;
pub(crate) mod claude_managed_integration;
pub(crate) mod claude_transcript;
pub mod cli;
pub(crate) mod codex_adapter;
mod codex_adopted;
pub(crate) mod codex_app_server;
pub(crate) mod codex_carry;
pub(crate) mod codex_history;
pub(crate) mod codex_hook;
pub mod codex_integration;
pub mod daemon;
pub(crate) mod downloads;
pub(crate) mod drift;
pub mod forward;
pub(crate) mod git_diff;
pub(crate) mod hook_common;
pub(crate) mod host_info;
pub mod host_protocol;
pub mod identity;
pub mod install;
pub mod ipc;
pub(crate) mod live_activity;
pub(crate) mod managed_session;
pub(crate) mod managed_worker;
#[cfg(test)]
mod netlab;
pub(crate) mod notify;
pub mod pairing;
pub(crate) mod pi_adapter;
pub(crate) mod pi_integration;
pub(crate) mod process;
pub mod protocol;
pub(crate) mod pty;
pub mod qr;
pub mod relay;
pub(crate) mod release_meta;
pub mod service;
pub(crate) mod slash_commands;
pub mod storage;
pub(crate) mod uploads;
pub(crate) mod workspace;
pub(crate) mod workspace_scan;
